name: murasame_playground
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.0.5"
  flutter: ^3.10.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  import_sorter: ^4.6.0
  # コマンド： flutter pub run import_sorter:main

  go_router: ^6.5.5

  shared_preferences: ^2.1.0

  flutter_rating_bar: ^4.0.1

  gap: ^3.0.0

  # 状態管理
  hooks_riverpod: ^2.3.4
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.0.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  # コマンド： flutter pub run build_runner build --delete-conflicting-outputs

  webview_flutter: ^4.2.2
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.1.6
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/ec_app/sample_data/sample_data.json
    - lib/ec_app/sample_data/images/